### ISSUE TITLE
Multiple interfaces of the same type.

### ISSUE THREAD

**Issue by crayfishx** [crayfishx/network_config#18]
It should be possible to configure two different interfaces of the same type, connected to separate VLAN's.

At the moment this is not possible, you can have:

```
network_config::interfaces:
  eth0: application
  eth1: application
```

however, you can't assign both eth0 and eth1 to different vlans because the simplification around this means you assign an interface type to a VLAN 

```
network_config::ifconfig:
  application:
    ipaddr: 10.0.0.1
    vlan: foo
```

This would bind both eth1 and eth2 to the foo VLAN with the same IP address, there is no way to bind them to separate VLAN's and IP's while inheriting the defaults from the interface type.
